#!/bin/bash

: ${USER_HOME?"Need to set the Home Directory"} ${DOTFILES_SRC?"Need to set the DOTFILES Directory"} ${DOTFILES_BKUP?"Need to set where you want to backup existing Dotfiles to"}

[[ ! -d "${DOTFILES_SRC}" ]] && echo "${DOTFILES_SRC} does not exists, please clone a repo.  Exiting ..." && exit 1;
