#!/bin/bash

DEFAULTS="${DEFAULTS:=~/default/dotfiles}"

(( $# >= 1 )) && USER_HOME=${1%/}
(( $# >= 2 )) && DOTFILES_SRC=${2%/}
(( $# >= 3 )) && DOTFILES_BKUP=${3%/}

[[ -e "${DEFAULTS}" ]] && . "${DEFAULTS}"

[[ -e "${DOTFILES_LOC}/lib/command_setup" ]] && . "${DOTFILES_LOC}/lib/command_setup"
[[ -e "${DOTFILES_LOC}/lib/update_home" ]] && . "${DOTFILES_LOC}/lib/update_home" || echo "Cannot find helper script aborting ..." && exit 1

install_dotfiles
. ~/.profile

l_question="Install GIT post-merge hook to auto-update on git pull - (Y)es, (N)o: "
l_result=$(confirm_move ${l_question})
if $l_result ; then
  echo ""
  echo ""
  lnk "Installing GIT Post Merge Hook" "${DOTFILES_GIT_WORK_TREE}/lib/post-merge.git_hook" "${DOTFILES_GIT_DIR}/hooks/post-merge"
fi
